CREATE DEFINER=`dulieutu`@`%` PROCEDURE `dulieutu_IT`.`11.updateDimT2`()
BEGIN
	
	ALTER TABLE Dim_TinhThanh 
	ADD COLUMN Lattitude decimal(10,5);
	
	ALTER TABLE Dim_TinhThanh 
	ADD COLUMN Longtitude decimal(10,5);

UPDATE Dim_TinhThanh Set Lattitude = 10.7 WHERE TinhThanh = 'An Giang';
UPDATE Dim_TinhThanh Set Lattitude = 10.4042 WHERE TinhThanh = 'Bà Rịa – Vũng Tàu';
UPDATE Dim_TinhThanh Set Lattitude = 21.2731 WHERE TinhThanh = 'Bắc Giang';
UPDATE Dim_TinhThanh Set Lattitude = 22.1333 WHERE TinhThanh = 'Bắc Kạn';
UPDATE Dim_TinhThanh Set Lattitude = 9.2833 WHERE TinhThanh = 'Bạc Liêu';
UPDATE Dim_TinhThanh Set Lattitude = 21.1861 WHERE TinhThanh = 'Bắc Ninh';
UPDATE Dim_TinhThanh Set Lattitude = 10.2333 WHERE TinhThanh = 'Bến Tre';
UPDATE Dim_TinhThanh Set Lattitude = 13.7765 WHERE TinhThanh = 'Bình Định';
UPDATE Dim_TinhThanh Set Lattitude = 11.0042 WHERE TinhThanh = 'Bình Dương';
UPDATE Dim_TinhThanh Set Lattitude = 11.6504 WHERE TinhThanh = 'Bình Phước';
UPDATE Dim_TinhThanh Set Lattitude = 10.9375 WHERE TinhThanh = 'Bình Thuận';
UPDATE Dim_TinhThanh Set Lattitude = 9.1833 WHERE TinhThanh = 'Cà Mau';
UPDATE Dim_TinhThanh Set Lattitude = 10.0333 WHERE TinhThanh = 'Cần Thơ';
UPDATE Dim_TinhThanh Set Lattitude = 22.6731 WHERE TinhThanh = 'Cao Bằng';
UPDATE Dim_TinhThanh Set Lattitude = 16.0748 WHERE TinhThanh = 'Đà Nẵng';
UPDATE Dim_TinhThanh Set Lattitude = 12.6667 WHERE TinhThanh = 'Đắk Lắk';
UPDATE Dim_TinhThanh Set Lattitude = 12.0042 WHERE TinhThanh = 'Đắk Nông';
UPDATE Dim_TinhThanh Set Lattitude = 21.3833 WHERE TinhThanh = 'Điện Biên';
UPDATE Dim_TinhThanh Set Lattitude = 10.9575 WHERE TinhThanh = 'Đồng Nai';
UPDATE Dim_TinhThanh Set Lattitude = 10.4603 WHERE TinhThanh = 'Đồng Tháp';
UPDATE Dim_TinhThanh Set Lattitude = 13.9833 WHERE TinhThanh = 'Gia Lai';
UPDATE Dim_TinhThanh Set Lattitude = 22.8233 WHERE TinhThanh = 'Hà Giang';
UPDATE Dim_TinhThanh Set Lattitude = 20.5453 WHERE TinhThanh = 'Hà Nam';
UPDATE Dim_TinhThanh Set Lattitude = 21.0245 WHERE TinhThanh = 'Hà Nội';
UPDATE Dim_TinhThanh Set Lattitude = 18.3428 WHERE TinhThanh = 'Hà Tĩnh';
UPDATE Dim_TinhThanh Set Lattitude = 20.9411 WHERE TinhThanh = 'Hải Dương';
UPDATE Dim_TinhThanh Set Lattitude = 20.8 WHERE TinhThanh = 'Hải Phòng';
UPDATE Dim_TinhThanh Set Lattitude = 9.7833 WHERE TinhThanh = 'Hậu Giang';
UPDATE Dim_TinhThanh Set Lattitude = 20.8172 WHERE TinhThanh = 'Hoà Bình';
UPDATE Dim_TinhThanh Set Lattitude = 20.6464 WHERE TinhThanh = 'Hưng Yên';
UPDATE Dim_TinhThanh Set Lattitude = 12.25 WHERE TinhThanh = 'Khánh Hoà';
UPDATE Dim_TinhThanh Set Lattitude = 10.2289 WHERE TinhThanh = 'Kiên Giang';
UPDATE Dim_TinhThanh Set Lattitude = 14.3417 WHERE TinhThanh = 'Kon Tum';
UPDATE Dim_TinhThanh Set Lattitude = 22.3991 WHERE TinhThanh = 'Lai Châu';
UPDATE Dim_TinhThanh Set Lattitude = 11.9359 WHERE TinhThanh = 'Lâm Đồng';
UPDATE Dim_TinhThanh Set Lattitude = 21.8478 WHERE TinhThanh = 'Lạng Sơn';
UPDATE Dim_TinhThanh Set Lattitude = 22.4194 WHERE TinhThanh = 'Lào Cai';
UPDATE Dim_TinhThanh Set Lattitude = 10.5322 WHERE TinhThanh = 'Long An';
UPDATE Dim_TinhThanh Set Lattitude = 20.42 WHERE TinhThanh = 'Nam Định';
UPDATE Dim_TinhThanh Set Lattitude = 18.6733 WHERE TinhThanh = 'Nghệ An';
UPDATE Dim_TinhThanh Set Lattitude = 20.2539 WHERE TinhThanh = 'Ninh Bình';
UPDATE Dim_TinhThanh Set Lattitude = 11.5643 WHERE TinhThanh = 'Ninh Thuận';
UPDATE Dim_TinhThanh Set Lattitude = 21.3228 WHERE TinhThanh = 'Phú Thọ';
UPDATE Dim_TinhThanh Set Lattitude = 13.0875 WHERE TinhThanh = 'Phú Yên';
UPDATE Dim_TinhThanh Set Lattitude = 17.4833 WHERE TinhThanh = 'Quảng Bình';
UPDATE Dim_TinhThanh Set Lattitude = 15.8733 WHERE TinhThanh = 'Quảng Nam';
UPDATE Dim_TinhThanh Set Lattitude = 15.1206 WHERE TinhThanh = 'Quảng Ngãi';
UPDATE Dim_TinhThanh Set Lattitude = 20.95 WHERE TinhThanh = 'Quảng Ninh';
UPDATE Dim_TinhThanh Set Lattitude = 16.7504 WHERE TinhThanh = 'Quảng Trị';
UPDATE Dim_TinhThanh Set Lattitude = 9.6 WHERE TinhThanh = 'Sóc Trăng';
UPDATE Dim_TinhThanh Set Lattitude = 21.327 WHERE TinhThanh = 'Sơn La';
UPDATE Dim_TinhThanh Set Lattitude = 11.3131 WHERE TinhThanh = 'Tây Ninh';
UPDATE Dim_TinhThanh Set Lattitude = 20.4461 WHERE TinhThanh = 'Thái Bình';
UPDATE Dim_TinhThanh Set Lattitude = 21.6 WHERE TinhThanh = 'Thái Nguyên';
UPDATE Dim_TinhThanh Set Lattitude = 19.8075 WHERE TinhThanh = 'Thanh Hoá';
UPDATE Dim_TinhThanh Set Lattitude = 16.4667 WHERE TinhThanh = 'Thừa Thiên Huế';
UPDATE Dim_TinhThanh Set Lattitude = 10.35 WHERE TinhThanh = 'Tiền Giang';
UPDATE Dim_TinhThanh Set Lattitude = 10.8167 WHERE TinhThanh = 'Hồ Chí Minh';
UPDATE Dim_TinhThanh Set Lattitude = 9.9369 WHERE TinhThanh = 'Trà Vinh';
UPDATE Dim_TinhThanh Set Lattitude = 21.8281 WHERE TinhThanh = 'Tuyên Quang';
UPDATE Dim_TinhThanh Set Lattitude = 10.255 WHERE TinhThanh = 'Vĩnh Long';
UPDATE Dim_TinhThanh Set Lattitude = 21.31 WHERE TinhThanh = 'Vĩnh Phúc';
UPDATE Dim_TinhThanh Set Lattitude = 21.7 WHERE TinhThanh = 'Yên Bái';
UPDATE Dim_TinhThanh Set Lattitude = 48.1369 WHERE TinhThanh = 'Khác';

UPDATE Dim_TinhThanh Set Longtitude = 105.1167 WHERE TinhThanh = 'An Giang';
UPDATE Dim_TinhThanh Set Longtitude = 107.1417 WHERE TinhThanh = 'Bà Rịa – Vũng Tàu';
UPDATE Dim_TinhThanh Set Longtitude = 106.1947 WHERE TinhThanh = 'Bắc Giang';
UPDATE Dim_TinhThanh Set Longtitude = 105.8333 WHERE TinhThanh = 'Bắc Kạn';
UPDATE Dim_TinhThanh Set Longtitude = 105.7167 WHERE TinhThanh = 'Bạc Liêu';
UPDATE Dim_TinhThanh Set Longtitude = 106.0763 WHERE TinhThanh = 'Bắc Ninh';
UPDATE Dim_TinhThanh Set Longtitude = 106.3833 WHERE TinhThanh = 'Bến Tre';
UPDATE Dim_TinhThanh Set Longtitude = 109.2237 WHERE TinhThanh = 'Bình Định';
UPDATE Dim_TinhThanh Set Longtitude = 106.6583 WHERE TinhThanh = 'Bình Dương';
UPDATE Dim_TinhThanh Set Longtitude = 106.6 WHERE TinhThanh = 'Bình Phước';
UPDATE Dim_TinhThanh Set Longtitude = 108.1583 WHERE TinhThanh = 'Bình Thuận';
UPDATE Dim_TinhThanh Set Longtitude = 105.15 WHERE TinhThanh = 'Cà Mau';
UPDATE Dim_TinhThanh Set Longtitude = 105.7833 WHERE TinhThanh = 'Cần Thơ';
UPDATE Dim_TinhThanh Set Longtitude = 106.25 WHERE TinhThanh = 'Cao Bằng';
UPDATE Dim_TinhThanh Set Longtitude = 108.224 WHERE TinhThanh = 'Đà Nẵng';
UPDATE Dim_TinhThanh Set Longtitude = 108.05 WHERE TinhThanh = 'Đắk Lắk';
UPDATE Dim_TinhThanh Set Longtitude = 107.6907 WHERE TinhThanh = 'Đắk Nông';
UPDATE Dim_TinhThanh Set Longtitude = 103.0169 WHERE TinhThanh = 'Điện Biên';
UPDATE Dim_TinhThanh Set Longtitude = 106.8426 WHERE TinhThanh = 'Đồng Nai';
UPDATE Dim_TinhThanh Set Longtitude = 105.6331 WHERE TinhThanh = 'Đồng Tháp';
UPDATE Dim_TinhThanh Set Longtitude = 108 WHERE TinhThanh = 'Gia Lai';
UPDATE Dim_TinhThanh Set Longtitude = 104.9836 WHERE TinhThanh = 'Hà Giang';
UPDATE Dim_TinhThanh Set Longtitude = 105.9122 WHERE TinhThanh = 'Hà Nam';
UPDATE Dim_TinhThanh Set Longtitude = 105.8412 WHERE TinhThanh = 'Hà Nội';
UPDATE Dim_TinhThanh Set Longtitude = 105.9058 WHERE TinhThanh = 'Hà Tĩnh';
UPDATE Dim_TinhThanh Set Longtitude = 106.3331 WHERE TinhThanh = 'Hải Dương';
UPDATE Dim_TinhThanh Set Longtitude = 106.6667 WHERE TinhThanh = 'Hải Phòng';
UPDATE Dim_TinhThanh Set Longtitude = 105.4708 WHERE TinhThanh = 'Hậu Giang';
UPDATE Dim_TinhThanh Set Longtitude = 105.3375 WHERE TinhThanh = 'Hoà Bình';
UPDATE Dim_TinhThanh Set Longtitude = 106.0511 WHERE TinhThanh = 'Hưng Yên';
UPDATE Dim_TinhThanh Set Longtitude = 109.1833 WHERE TinhThanh = 'Khánh Hoà';
UPDATE Dim_TinhThanh Set Longtitude = 103.9572 WHERE TinhThanh = 'Kiên Giang';
UPDATE Dim_TinhThanh Set Longtitude = 107.9792 WHERE TinhThanh = 'Kon Tum';
UPDATE Dim_TinhThanh Set Longtitude = 103.4393 WHERE TinhThanh = 'Lai Châu';
UPDATE Dim_TinhThanh Set Longtitude = 108.4429 WHERE TinhThanh = 'Lâm Đồng';
UPDATE Dim_TinhThanh Set Longtitude = 106.7578 WHERE TinhThanh = 'Lạng Sơn';
UPDATE Dim_TinhThanh Set Longtitude = 103.995 WHERE TinhThanh = 'Lào Cai';
UPDATE Dim_TinhThanh Set Longtitude = 106.4042 WHERE TinhThanh = 'Long An';
UPDATE Dim_TinhThanh Set Longtitude = 106.1683 WHERE TinhThanh = 'Nam Định';
UPDATE Dim_TinhThanh Set Longtitude = 105.6922 WHERE TinhThanh = 'Nghệ An';
UPDATE Dim_TinhThanh Set Longtitude = 105.975 WHERE TinhThanh = 'Ninh Bình';
UPDATE Dim_TinhThanh Set Longtitude = 108.9886 WHERE TinhThanh = 'Ninh Thuận';
UPDATE Dim_TinhThanh Set Longtitude = 105.4019 WHERE TinhThanh = 'Phú Thọ';
UPDATE Dim_TinhThanh Set Longtitude = 109.3106 WHERE TinhThanh = 'Phú Yên';
UPDATE Dim_TinhThanh Set Longtitude = 106.6 WHERE TinhThanh = 'Quảng Bình';
UPDATE Dim_TinhThanh Set Longtitude = 108.3327 WHERE TinhThanh = 'Quảng Nam';
UPDATE Dim_TinhThanh Set Longtitude = 108.7922 WHERE TinhThanh = 'Quảng Ngãi';
UPDATE Dim_TinhThanh Set Longtitude = 107.0833 WHERE TinhThanh = 'Quảng Ninh';
UPDATE Dim_TinhThanh Set Longtitude = 107.2 WHERE TinhThanh = 'Quảng Trị';
UPDATE Dim_TinhThanh Set Longtitude = 105.9719 WHERE TinhThanh = 'Sóc Trăng';
UPDATE Dim_TinhThanh Set Longtitude = 103.9141 WHERE TinhThanh = 'Sơn La';
UPDATE Dim_TinhThanh Set Longtitude = 106.0963 WHERE TinhThanh = 'Tây Ninh';
UPDATE Dim_TinhThanh Set Longtitude = 106.3422 WHERE TinhThanh = 'Thái Bình';
UPDATE Dim_TinhThanh Set Longtitude = 105.85 WHERE TinhThanh = 'Thái Nguyên';
UPDATE Dim_TinhThanh Set Longtitude = 105.7764 WHERE TinhThanh = 'Thanh Hoá';
UPDATE Dim_TinhThanh Set Longtitude = 107.5833 WHERE TinhThanh = 'Thừa Thiên Huế';
UPDATE Dim_TinhThanh Set Longtitude = 106.35 WHERE TinhThanh = 'Tiền Giang';
UPDATE Dim_TinhThanh Set Longtitude = 106.6333 WHERE TinhThanh = 'Hồ Chí Minh';
UPDATE Dim_TinhThanh Set Longtitude = 106.3411 WHERE TinhThanh = 'Trà Vinh';
UPDATE Dim_TinhThanh Set Longtitude = 105.2156 WHERE TinhThanh = 'Tuyên Quang';
UPDATE Dim_TinhThanh Set Longtitude = 105.9753 WHERE TinhThanh = 'Vĩnh Long';
UPDATE Dim_TinhThanh Set Longtitude = 105.5967 WHERE TinhThanh = 'Vĩnh Phúc';
UPDATE Dim_TinhThanh Set Longtitude = 104.8667 WHERE TinhThanh = 'Yên Bái';
UPDATE Dim_TinhThanh Set Longtitude = 11.5753 WHERE TinhThanh = 'Khác';

END