CREATE DEFINER=`dulieutu`@`%` PROCEDURE `dulieutu_IT`.`3.mappingStg1`()
BEGIN
		-- CapBac
	
	ALTER TABLE Stg_CapBac
ADD COLUMN IF NOT EXISTS CapBacMap VARCHAR(50);

UPDATE Stg_CapBac  
SET     CapBacMap =  CASE  
                        WHEN lower(CapBac) Like '%phòng%'  THEN 'Trưởng/Phó phòng' 
                        WHEN lower(CapBac) Like '%nhóm%'  THEN 'Trưởng nhóm' 
                        WHEN lower(CapBac) Like '%leader%'  THEN 'Trưởng nhóm' 
                        WHEN lower(CapBac) Like '%team%'  THEN 'Trưởng/Phó nhóm' 
                        WHEN lower(CapBac) Like '%giám đốc%'  THEN 'Giám đốc/Phó GĐ' 
                        WHEN lower(CapBac) Like '%quản lý%'  THEN 'Quản lý' 
                        WHEN lower(CapBac) Like '%manager%'  THEN 'Quản lý' 
                        WHEN lower(CapBac) Like '%thực tập%'  THEN 'Thực tập sinh' 
                        WHEN lower(CapBac) Like '%intern%'  THEN 'Thực tập sinh' 
                        ELSE 'Nhân viên'
END ;

-- LoaiHinh
ALTER TABLE Stg_LoaiHinh
ADD COLUMN IF NOT EXISTS LoaiHinhMap VARCHAR(50);

UPDATE Stg_LoaiHinh  
SET     LoaiHinhMap =  CASE  
                        WHEN lower(LoaiHinh) Like '%toàn%'  THEN 'Toàn thời gian' 
                        WHEN lower(LoaiHinh) Like '%bán%'  THEN 'Bán thời gian' 
                        WHEN lower(LoaiHinh) Like '%part%'  THEN 'Bán thời gian' 
                        WHEN lower(LoaiHinh) Like '%thực tập%'  THEN 'Bán thời gian' 
                        WHEN lower(LoaiHinh) Like '%full%'  THEN 'Bán thời gian' 
                        WHEN lower(LoaiHinh) Like '%khác%'  THEN 'Hình thức khác' 
                        WHEN lower(LoaiHinh) Like '%hybrid%'  THEN 'Hình thức khác' 
                        WHEN lower(LoaiHinh) Like '%remote%'  THEN 'Hình thức khác' 
                        ELSE 'Toàn thời gian'
                        
END ;

-- DiaDiem

ALTER TABLE Stg_DiaDiem
ADD COLUMN  TinhThanh VARCHAR(100);

UPDATE Stg_DiaDiem  
SET     TinhThanh =  CASE  
When lower(DiaDiem) Like '%an giang%'  THEN 'An Giang'
When lower(DiaDiem) Like '%bà r%'  THEN 'Bà Rịa – Vũng Tàu'
When lower(DiaDiem) Like '%vũng tàu%'  THEN 'Bà Rịa – Vũng Tàu'
When lower(DiaDiem) Like '%bắc giang%'  THEN 'Bắc Giang'
When lower(DiaDiem) Like '%bắc kạn%'  THEN 'Bắc Kạn'
When lower(DiaDiem) Like '%bạc liêu%'  THEN 'Bạc Liêu'
When lower(DiaDiem) Like '%bắc ninh%'  THEN 'Bắc Ninh'
When lower(DiaDiem) Like '%bến tre%'  THEN 'Bến Tre'
When lower(DiaDiem) Like '%bình định%'  THEN 'Bình Định'
When lower(DiaDiem) Like '%bình dương%'  THEN 'Bình Dương'
When lower(DiaDiem) Like '%bình phước%'  THEN 'Bình Phước'
When lower(DiaDiem) Like '%bình thuận%'  THEN 'Bình Thuận'
When lower(DiaDiem) Like '%cà mau%'  THEN 'Cà Mau'
When lower(DiaDiem) Like '%cần thơ%'  THEN 'Cần Thơ'
When lower(DiaDiem) Like '%cao bằng%'  THEN 'Cao Bằng'
When lower(DiaDiem) Like '%đà nẵng%'  THEN 'Đà Nẵng'
When lower(DiaDiem) Like '%đắk lắk%'  THEN 'Đắk Lắk'
When lower(DiaDiem) Like '%đắk nông%'  THEN 'Đắk Nông'
When lower(DiaDiem) Like '%điện biên%'  THEN 'Điện Biên'
When lower(DiaDiem) Like '%đồng nai%'  THEN 'Đồng Nai'
When lower(DiaDiem) Like '%đồng tháp%'  THEN 'Đồng Tháp'
When lower(DiaDiem) Like '%gia lai%'  THEN 'Gia Lai'
When lower(DiaDiem) Like '%hà giang%'  THEN 'Hà Giang'
When lower(DiaDiem) Like '%hà nam%'  THEN 'Hà Nam'
When lower(DiaDiem) Like '%hà nội%'  THEN 'Hà Nội'
When lower(DiaDiem) Like '%hn%'  THEN 'Hà Nội'
When lower(DiaDiem) Like '%hà tĩnh%'  THEN 'Hà Tĩnh'
When lower(DiaDiem) Like '%hải dương%'  THEN 'Hải Dương'
When lower(DiaDiem) Like '%hải phòng%'  THEN 'Hải Phòng'
When lower(DiaDiem) Like '%hậu giang%'  THEN 'Hậu Giang'
When lower(DiaDiem) Like '%a bình%'  THEN 'Hoà Bình'
When lower(DiaDiem) Like '%hưng yên%'  THEN 'Hưng Yên'
When lower(DiaDiem) Like '%khánh h%'  THEN 'Khánh Hoà'
When lower(DiaDiem) Like '%kiên giang%'  THEN 'Kiên Giang'
When lower(DiaDiem) Like '%kon tum%'  THEN 'Kon Tum'
When lower(DiaDiem) Like '%lai châu%'  THEN 'Lai Châu'
When lower(DiaDiem) Like '%lâm đồng%'  THEN 'Lâm Đồng'
When lower(DiaDiem) Like '%lạng sơn%'  THEN 'Lạng Sơn'
When lower(DiaDiem) Like '%lào cai%'  THEN 'Lào Cai'
When lower(DiaDiem) Like '%long an%'  THEN 'Long An'
When lower(DiaDiem) Like '%nam định%'  THEN 'Nam Định'
When lower(DiaDiem) Like '%nghệ an%'  THEN 'Nghệ An'
When lower(DiaDiem) Like '%ninh bình%'  THEN 'Ninh Bình'
When lower(DiaDiem) Like '%ninh thuận%'  THEN 'Ninh Thuận'
When lower(DiaDiem) Like '%phú thọ%'  THEN 'Phú Thọ'
When lower(DiaDiem) Like '%phú yên%'  THEN 'Phú Yên'
When lower(DiaDiem) Like '%quảng bình%'  THEN 'Quảng Bình'
When lower(DiaDiem) Like '%quảng nam%'  THEN 'Quảng Nam'
When lower(DiaDiem) Like '%quảng ngãi%'  THEN 'Quảng Ngãi'
When lower(DiaDiem) Like '%quảng ninh%'  THEN 'Quảng Ninh'
When lower(DiaDiem) Like '%quảng trị%'  THEN 'Quảng Trị'
When lower(DiaDiem) Like '%sóc trăng%'  THEN 'Sóc Trăng'
When lower(DiaDiem) Like '%sơn la%'  THEN 'Sơn La'
When lower(DiaDiem) Like '%tây ninh%'  THEN 'Tây Ninh'
When lower(DiaDiem) Like '%thái bình%'  THEN 'Thái Bình'
When lower(DiaDiem) Like '%thái nguyên%'  THEN 'Thái Nguyên'
When lower(DiaDiem) Like '%thanh h%'  THEN 'Thanh Hoá'
When lower(DiaDiem) Like '%thừa t%'  THEN 'Thừa Thiên Huế'
When lower(DiaDiem) Like '%tiền giang%'  THEN 'Tiền Giang'
When lower(DiaDiem) Like '%hồ%'  THEN 'Hồ Chí Minh'
When lower(DiaDiem) Like '%hcm%'  THEN 'Hồ Chí Minh'
When lower(DiaDiem) Like '%trà vinh%'  THEN 'Trà Vinh'
When lower(DiaDiem) Like '%tuyên quang%'  THEN 'Tuyên Quang'
When lower(DiaDiem) Like '%vĩnh long%'  THEN 'Vĩnh Long'
When lower(DiaDiem) Like '%vĩnh phúc%'  THEN 'Vĩnh Phúc'
When lower(DiaDiem) Like '%yên bái%'  THEN 'Yên Bái'
                        ELSE 'Khác'
END ;

-- CongViec
ALTER TABLE Stg_CongViec
ADD COLUMN  CongViec text;

UPDATE Stg_CongViec  
SET     CongViec =  CASE 
	When lower(TenCV) Like '%giám đốc%'  THEN 'IT Director'
	When lower(TenCV) Like '%trưởng nhóm%'  THEN 'IT Leader'
	When lower(TenCV) Like '%leader%'  THEN 'IT Leader'
	When lower(TenCV) Like '%pm%'  THEN 'Project Manager'
	When lower(TenCV) Like '%scrum%'  THEN 'Scrum Master'
	When lower(TenCV) Like '%project%'  THEN 'Project Manager'
	When lower(TenCV) Like '%phân tích nghiệp vụ%'  THEN 'BA'
	When lower(TenCV) Like '%phân tích dữ liệu%'  THEN 'DA'
	When lower(TenCV) Like '%dba%'  THEN 'DBA'
	When lower(TenCV) Like '%data scien%'  THEN 'DS'
	When lower(TenCV) Like '%data engin%'  THEN 'DE'
	When lower(TenCV) Like '%2d%'  THEN 'Graphic Designer'
	When lower(TenCV) Like '%3d%'  THEN 'Graphic Designer'
	When lower(TenCV) Like '%đồ h%'  THEN 'Graphic Designer'
	When lower(TenCV) Like '%design%'  THEN 'Graphic Designer'
	When lower(TenCV) Like '%thiết kế%'  THEN 'Graphic Designer'
	When lower(TenCV) Like '%business analy%'  THEN 'BA'
	When lower(TenCV) Like '%tester%'  THEN 'Tester'
	When lower(TenCV) Like '%qc%'  THEN 'QA/QC Specialist'
	When lower(TenCV) Like '%qa%'  THEN 'QA/QC Specialist'
	When lower(TenCV) Like '%product%'  THEN 'Product Manager'
	When lower(TenCV) Like '%sản phẩm%'  THEN 'Product Manager'
	When lower(TenCV) Like '%it support%'  THEN 'IT Support'
	When lower(TenCV) Like '%it staff%'  THEN 'IT staff'
	When lower(TenCV) Like '%viên it%'  THEN 'IT Staff'
	When lower(TenCV) Like '%helpdesk%'  THEN 'IT Staff'
	When lower(TenCV) Like '%front%'  THEN 'Frontend Dev'
	When lower(TenCV) Like '%back%'  THEN 'Backend Dev'
	When lower(TenCV) Like '%full%'  THEN 'Fullstack Dev'
	When lower(TenCV) Like '%brse%'  THEN 'Bridge System Engineer'
	When lower(TenCV) Like '%cầu nối%'  THEN 'Bridge System Engineer'
	When lower(TenCV) Like '%network%'  THEN 'Network Administrator'
	When lower(TenCV) Like '%mạng%'  THEN 'Network Administrator'
	When lower(TenCV) Like '%an ninh%'  THEN 'Security Administrator'
	When lower(TenCV) Like '%bảo mật%'  THEN 'Security Administrator'
	When lower(TenCV) Like '%an toàn%'  THEN 'Security Administrator'
	When lower(TenCV) Like '%security%'  THEN 'Security Administrator'
	When lower(TenCV) Like '%mobile%'  THEN 'Mobile/App Dev'
	When lower(TenCV) Like '%app%'  THEN 'Mobile/App Dev'
	When lower(TenCV) Like '%ứng dụng%'  THEN 'Mobile/App Dev'
	When lower(TenCV) Like '%ios%'  THEN 'Mobile/App Dev'
	When lower(TenCV) Like '%android%'  THEN 'Mobile/App Dev'
	When lower(TenCV) Like '%devop%'  THEN 'DevOps'
	When lower(TenCV) Like '%embedded%'  THEN 'Embedded Dev'
	When lower(TenCV) Like '%nhúng%'  THEN 'Embedded Dev'
	When lower(TenCV) Like '%game%'  THEN 'Game Dev'
	When lower(TenCV) Like '%seo%'  THEN 'SEO Specialist'
	When lower(TenCV) Like '%quản trị dữ liệu%'  THEN 'DBA'
	When lower(TenCV) Like '%dự án%'  THEN 'Project Manager'
	When lower(TenCV) Like '%quality%'  THEN 'QA/QC Specialist'
	When lower(TenCV) Like '%chất lượng%'  THEN 'QA/QC Specialist'
	When lower(TenCV) Like '%test%'  THEN 'Tester'
	When lower(TenCV) Like '%bảo hành%'  THEN 'Tester'
	When lower(TenCV) Like '%bảo trì%'  THEN 'Tester'
	When lower(TenCV) Like '%cơ sở dữ liệu%'  THEN 'DBA'
	When lower(TenCV) Like '%cloud%'  THEN 'System Administrator'
	When lower(TenCV) Like '%web%'  THEN 'Web Dev'
	When lower(TenCV) Like '%wordpress%'  THEN 'Web Dev'
	When lower(TenCV) Like '%it manager%'  THEN 'IT manager'
	When lower(TenCV) Like '%software%'  THEN 'Software Dev'
	When lower(TenCV) Like '%admin%'  THEN 'System Administrator'
	When lower(TenCV) Like '%comto%'  THEN 'IT Comtor'
	When lower(TenCV) Like '%system%'  THEN 'System Administrator'
	When lower(TenCV) Like '%hệ thống%'  THEN 'System Administrator'
	When lower(TenCV) Like '%rủi ro%'  THEN 'Risk Administrator'
	When lower(TenCV) Like '%risk%'  THEN 'Risk Administrator'
	When lower(TenCV) Like '%dữ liệu phân tích%'  THEN 'DA'
	When lower(TenCV) Like '%data analy%'  THEN 'DA'
	When lower(TenCV) Like '%business senior analyst%'  THEN 'BA'
	When lower(TenCV) Like '%manager%'  THEN 'IT manager'
	When lower(TenCV) Like '%superv%'  THEN 'QA/QC Specialist'
	When lower(TenCV) Like '%code%'  THEN 'Dev'
	When lower(TenCV) Like '%program%'  THEN 'Dev'
	When lower(TenCV) Like '%hỗ trợ kĩ thuật%'  THEN 'IT Support'
	When lower(TenCV) Like '%hỗ trợ kỹ thuật%'  THEN 'IT Support'
	When lower(TenCV) Like '%business intell%'  THEN 'DA'
	When lower(TenCV) Like '%solution architect%'  THEN 'Solution Architect'
	When lower(TenCV) Like '%sư dữ liệu%'  THEN 'DE'
	When lower(TenCV) Like '%plan%'  THEN 'Project Manager'
	When lower(TenCV) Like '%support%'  THEN 'IT Support'
	When lower(TenCV) Like '%qe%'  THEN 'QA/QC Specialist'
	When lower(TenCV) Like '% ui%'  THEN 'Graphic Designer'
	When lower(TenCV) Like '%ux %'  THEN 'Graphic Designer'
	When lower(TenCV) Like '%Data%'  THEN 'DA'
	When lower(TenCV) Like '%nhân viên công nghệ%'  THEN 'IT Support'
	When lower(TenCV) Like '%ai engin%'  THEN 'AI/ML Engineer'
	When lower(TenCV) Like '%kĩ thuật%'  THEN 'IT Support'
	When lower(TenCV) Like '%kỹ thuật%'  THEN 'IT Support'
	When lower(TenCV) Like '%phần mềm%'  THEN 'Software Dev'
	When lower(TenCV) Like '%js %'  THEN 'IT Support'
	When lower(TenCV) Like '%lead%'  THEN 'IT Leader'
	When lower(TenCV) Like '%comm%'  THEN 'IT Comtor'
	When lower(TenCV) Like '%ruby%'  THEN 'Web Dev'
	When lower(TenCV) Like '%hỗ trợ%'  THEN 'IT Support'
	When lower(TenCV) Like '%xử lý dữ liệu%'  THEN 'DS'
	When lower(TenCV) Like '% ai %'  THEN 'AI/ML Engineer'
	When lower(TenCV) Like '%ai resear%'  THEN 'IT Support'
	When lower(TenCV) Like '%bridge%'  THEN 'Bridge System Engineer'
	When lower(TenCV) Like '%php%'  THEN 'Web Dev'
	When lower(TenCV) Like '%aws%'  THEN 'System Administrator'
	When lower(TenCV) Like '%sap%'  THEN 'Software Dev'
	When lower(TenCV) Like '%consultant%'  THEN 'IT Consultant'
	When lower(TenCV) Like '%tư vấn%'  THEN 'IT Consultant'
	When lower(TenCV) Like '%process%'  THEN 'QA/QC Specialist'
	When lower(TenCV) Like '%oracle%'  THEN 'DBA'
	When lower(TenCV) Like '%machine learn%'  THEN 'AI/ML Engineer'
	When lower(TenCV) Like '%dữ liệu%'  THEN 'DA'
	When lower(TenCV) Like '%power bi%'  THEN 'DA'
	When lower(TenCV) Like '%wifi%'  THEN 'Network Administrator'
	When lower(TenCV) Like '%mạng%'  THEN 'Network Administrator'
	When lower(TenCV) Like '%modeler%'  THEN 'Project Manager'
	When lower(TenCV) Like '%infrastructure%'  THEN 'System Administrator'
	When lower(TenCV) Like '%domain%'  THEN 'System Administrator'
	When lower(TenCV) Like '%it assist%'  THEN 'IT Support'
	When lower(TenCV) Like '%photoshop%'  THEN 'Graphic Designer'
	When lower(TenCV) Like '%quản trị hệ thống%'  THEN 'System Administrator'	
	When lower(TenCV) Like '%unity%'  THEN 'Game Dev'
	When lower(TenCV) Like '%iot%'  THEN 'Software Dev'
	When lower(TenCV) Like '%firmware%'  THEN 'System Administrator'
	When lower(TenCV) Like '%hạ tầng%'  THEN 'System Administrator'
	When lower(TenCV) Like '%phân tích số liệu%'  THEN 'DA'
	When lower(TenCV) Like '%c++%'  THEN 'Dev'
	When lower(TenCV) Like '%c#%'  THEN 'Dev'
	When lower(TenCV) Like '%.net %'  THEN 'Dev'
	When lower(TenCV) Like '%dotnet%'  THEN 'Dev'
	When lower(TenCV) Like '%kiểm thử%'  THEN 'Tester'
	When lower(TenCV) Like '%react%'  THEN 'Mobile/App Dev'
	When lower(TenCV) Like '%python%'  THEN 'DS'
	When lower(TenCV) Like '%ai content%'  THEN 'AI/ML Engineer'
	When lower(TenCV) Like '%vẽ%'  THEN 'Art Designer'
	When lower(TenCV) Like '%cad%'  THEN 'Art Designer'
	When lower(TenCV) Like '%technical ar%'  THEN 'Technical Architect'
	When lower(TenCV) Like '%trưởng phòng it%'  THEN 'IT Leader'
	When lower(TenCV) Like '%html%'  THEN 'Web Dev'
	When lower(TenCV) Like '%blockchain%'  THEN 'Software Dev'
	When lower(TenCV) Like '%iot%'  THEN 'Software Dev'
	When lower(TenCV) Like '%phần mềm%'  THEN 'Software Dev'
	When lower(TenCV) Like '%cto%'  THEN 'IT Director'
	When lower(TenCV) Like '%cio%'  THEN 'IT Director'
	When lower(TenCV) Like '%flutter%'  THEN 'Web Dev'
	When lower(TenCV) Like '%trí tuệ nhân tạo%'  THEN 'AI/ML Engineer'
	When lower(TenCV) Like '%java%'  THEN 'Mobile/App Dev'
	When lower(TenCV) Like '%ux/ui%'  THEN 'Graphic Designer'
	When lower(TenCV) Like '%phần cứng%'  THEN 'System Administrator'
	When lower(TenCV) Like '%js,%'  THEN 'Web Dev'
	When lower(TenCV) Like '%lập trình viên%'  THEN 'Dev'
	When lower(TenCV) Like '%lập trình%'  THEN 'Dev'
	When lower(TenCV) Like '%developer%'  THEN 'Dev'
	ELSE 'Khác'
	
END;
END